# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64\x65mo1.proto\"\x17\n\x07request\x12\x0c\n\x04\x64\x61ta\x18\n \x01(\x03\"\x17\n\x08response\x12\x0b\n\x03res\x18\x14 \x01(\x03\x32/\n\rdemo1_service\x12\x1e\n\x05hello\x12\x08.request\x1a\t.response\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['request']
_RESPONSE = DESCRIPTOR.message_types_by_name['response']
request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'demo1_pb2'
  # @@protoc_insertion_point(class_scope:request)
  })
_sym_db.RegisterMessage(request)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'demo1_pb2'
  # @@protoc_insertion_point(class_scope:response)
  })
_sym_db.RegisterMessage(response)

_DEMO1_SERVICE = DESCRIPTOR.services_by_name['demo1_service']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=15
  _REQUEST._serialized_end=38
  _RESPONSE._serialized_start=40
  _RESPONSE._serialized_end=63
  _DEMO1_SERVICE._serialized_start=65
  _DEMO1_SERVICE._serialized_end=112
# @@protoc_insertion_point(module_scope)
