postgres:
  database: intersystem
  user: postgres
  password: root
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5
workers:
    max_workers: 5
    model_path:
      classes: "model/data/traffic_light.names"
      weights: "model/data/best_model_12.pt"
      cfg: "model/data/yolov3-spp-6cls.cfg"